export const sampleMovements = [
  { id: 'm1', kind: 'GASTO', date: '2025-11-01', amount: 12.5, sourceOrReason: 'Café y snack', status: 'CONFIRMADO' },
  { id: 'm2', kind: 'INGRESO', date: '2025-11-02', amount: 500, sourceOrReason: 'Trabajo freelance', status: 'CONFIRMADO' },
  { id: 'm3', kind: 'GASTO', date: '2025-11-03', amount: 1200, sourceOrReason: 'Renta', status: 'CONFIRMADO' },
  { id: 'm4', kind: 'GASTO', date: '2025-11-05', amount: 40, sourceOrReason: 'Supermercado', status: 'CONFIRMADO' },
  { id: 'm5', kind: 'INGRESO', date: '2025-11-10', amount: 1500, sourceOrReason: 'Sueldo', status: 'CONFIRMADO' },
  { id: 'm6', kind: 'GASTO', date: '2025-11-12', amount: 60, sourceOrReason: 'Transporte', status: 'CONFIRMADO' },
  { id: 'm7', kind: 'GASTO', date: '2025-11-15', amount: 85, sourceOrReason: 'Cena afuera', status: 'CONFIRMADO' },
  { id: 'm8', kind: 'INGRESO', date: '2025-11-25', amount: 300, sourceOrReason: 'Ingreso futuro', status: 'PLANIFICADO' },
]

export const sampleObjectives = [
  {
    id: 'obj1',
    name: 'Ahorrar 3000 para mudarme',
    area: 'FINANZAS',
    status: 'ACTIVO',
    priorityLevel: 'ALTA',
    description: 'Crear un fondo para mudarme a un lugar más cómodo.',
    startDate: '2025-11-01',
    endDate: '2026-04-30',
    targetValue: 3000,
    currentValue: 1050,
  },
  {
    id: 'obj2',
    name: 'Ordenar finanzas del mes',
    area: 'FINANZAS',
    status: 'ACTIVO',
    priorityLevel: 'MEDIA',
    description: 'Tener todos los gastos e ingresos del mes registrados.',
    startDate: '2025-11-01',
    endDate: '2025-11-30',
    targetValue: 0,
    currentValue: 0,
  },
  {
    id: 'obj3',
    name: 'Mejorar salud caminando 3 veces por semana',
    area: 'SALUD',
    status: 'PAUSADO',
    priorityLevel: 'BAJA',
    description: '',
    startDate: '2025-10-01',
    endDate: '2025-12-31',
    targetValue: 0,
    currentValue: 0,
  },
]

export const sampleActivities = [
  {
    id: 'act1',
    date: '2025-11-28',
    name: 'Registrar gastos del día',
    description: 'Anotar todos los movimientos de hoy en la app.',
    type: 'FINANCIERA',
    objectiveId: 'obj2',
    status: 'HECHA',
  },
  {
    id: 'act2',
    date: '2025-11-29',
    name: 'Revisión rápida de ingresos',
    description: 'Verificar que todos los ingresos del mes estén cargados.',
    type: 'FINANCIERA',
    objectiveId: 'obj2',
    status: 'HECHA',
  },
  {
    id: 'act3',
    date: '2025-11-30',
    name: 'Plan de ahorro para mudanza',
    description: 'Definir cuánto separar por semana.',
    type: 'FINANCIERA',
    objectiveId: 'obj1',
    status: 'PENDIENTE',
  },
  {
    id: 'act4',
    date: '2025-12-01',
    name: 'Cargar gastos pendientes',
    description: 'Cargar en la app todos los tickets que faltan.',
    type: 'FINANCIERA',
    objectiveId: 'obj2',
    status: 'PENDIENTE',
  },
]
